# Generated by Django 2.2.16 on 2022-10-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221028_2229'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user can not be a author',
        ),
    ]
