# Generated by Django 2.2.16 on 2022-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20221028_2241'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user can not be a author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='user can not be a author'),
        ),
    ]
