# Generated by Django 2.2.16 on 2022-10-28 20:32

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20221028_2326'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user can not be a author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='user is not author'),
        ),
    ]
