# Generated by Django 2.2.16 on 2022-10-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221028_2332'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user is not author',
        ),
    ]
